### ISSUE TITLE
request: total backup time

### ISSUE THREAD

**Issue by brogel** [HandyGuySoftware/dupReport#102]
First off, i'm not sure this is the correct location to post this. as this is my very first post on Github. 
Very sorry if this has to be posted somewhere else.

My request:
Is there a possibility to add the total runtime of a backup? In every report send by Duplicati there is the begin and end time of the backup, so the total time can be calculated. 
I think its strange this is not yet implemented as it is something so 'basic', so maybe there is a problem to add this.

**Comment by HandyGuySoftware** [comment]
@brogel, this is certainly the right place to post, welcome! There shouldn't be a problem adding total runtime, I guess nobody ever asked for it before ;-) I'll take a look at the code and see how it can be implemented. Thanks for the suggestion!

HG

**Comment by HandyGuySoftware** [comment]
@brogel, I just uploaded some test code to the Issue_102 branch here on GitHub. This code adds a "Duration" column to the reports to show the duration of the backup. Please download it to your system and see if it works properly for you.

**WARNING**: The new code will update the structure of your database and config files (dupreport.db and dupreport.rc). **PLEASE BACK UP THESE TWO FILES** before running the new code - just in case ;-)

Let me know how it works. Hopefully well, and I can move it to the pre_prod branch for more testing.

HG

**Comment by brogel** [comment]
@HandyGuySoftware , thank you very much working perfectly.
some nitpicking, you could improve styling by letting it remove the zero values. Now i have a backup that ran 0d 0h 0m 58s. But like i said this is just a small detail. 

Thanks again for the quick response and solution.

FYI: i tested it on a RPI 3b with the lastest Raspian 9 "stretch".

**Comment by HandyGuySoftware** [comment]
I changed the reporting routine and the .rc file to allow suppression of "zero" units in the duration display. This is triggered by adding
`durationzeroes = false`
in the [report] section of the .rc file. You will need to add this line manually in the .rc file, as the default case is 
`durationzeroes = true`

Updated code in the Issue_102 branch. Please download it and have a run at it to see if that works better for you.

HG

**Comment by mr-flibble** [comment]
Hello, thank you for Issue_102 branch. 
I upgraded from version 2.0.1
but I'm getting **SQLite error: no such column: dbSeen**

```
B:\folder\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\python.exe "B:\folder\dupReport_test\dupReport.py"
Database file B:\folder\dupReport_test/dupReport.db is out of date. Needs update to latest version.
Need to upgrade database B:\folder\dupReport_test/dupReport.db from version 101 to version 102
Database file B:\folder\dupReport_test/dupReport.db has been updated to the latest version.
SQLite error: no such column: dbSeen
```

log content
```
******** dupReport Log - Start: Sat Dec 15 17:54:52 2018
Program Version 2.2.4 Beta 1
Database Version 1.0.2
Python version 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
Program Path=B:\folder\dupReport_test
initOptions()
Processing command line...
options.processCmdLineArgs()
Command line parsed. args=[Namespace(Version=False, append=False, collect=False, dbpath=None, file=None, initdb=False, logpath=None, nomail=False, purgedb=False, rcpath=None, remove=None, report=False, rollback=None, rollbackx=None, size=None, stopbackupwarn=False, verbose=None)]
RC path not specified on command line. Using default: B:\folder\dupReport_test.
RC path=[B:\folder\dupReport_test/dupReport.rc]
options.openRcFile(B:\folder\dupReport_test/dupReport.rc)
options.checkRcFileVersion()
RC file versions: current=210 new=210.
Current version number=210. Need to upgrade rc file? False
options.setRcDefaults()
rc.setDefaults(B:\folder\dupReport_test/dupReport.rc)
newRc=False
options.readRcOptions(B:\folder\dupReport_test/dupReport.rc)
Parsed config options=...

Need to restart? False
Program initialization complete. Continuing program.
Database.__init__(B:\folder\dupReport_test/dupReport.db)
Database.checkDbVersion()
Database.execSqlStmt(): Executing SQL command.
SQL stmt=[SELECT major, minor, subminor FROM version WHERE desc = 'database']
Database: current version=101  new version=102
Converting database to version 1.0.2
Database.execSqlStmt(): Executing SQL command.
SQL stmt=[UPDATE version SET major = 1, minor = 0, subminor = 2 WHERE desc = 'database']
Database.execSqlStmt(): Executing SQL command.
SQL stmt=[ALTER TABLE report ADD COLUMN duration real]
Database.execSqlStmt(): Executing SQL command.
SQL stmt=[UPDATE report SET duration = 0]
Database.dbCommit(): Commiting transaction.

Logfile=[B:\folder\dupReport_test/dupReport.log]  appendlog=[False]  logLevel=[2]
dbPath=[B:\folder\dupReport_test/dupReport.db]  rcpath=[B:\folder\dupReport_test/dupReport.rc]
Database.execSqlStmt(): Executing SQL command.
SQL stmt=[UPDATE emails SET dbSeen = 0]
SQLite error: no such column: dbSeen

Closing everything...
Closing inbound email server...
Closing outbound email server...
Closing database file...
Database.dbClose(): Closing database object.
Closing log file...
```


Did I did something wrong? Thanks 
(I have backup)

EDIT: Added log level 3 output

**Comment by HandyGuySoftware** [comment]
@mr-flibble , it appears that the DB was never properly upgraded to version 101, that's when the dbSeen column would have been added. Odd, since the problem just appeared and not having a dbSeen column should have crashed the program long before this. 

Do you have access to a SQLite database browser? If so, can you post the contents of the version table from the original (pre-Issue_102-upgrade) db?

If possible, can you also post the whole DB schema from the pre-upgrade DB?

**Comment by mr-flibble** [comment]
Hello @HandyGuySoftware , thanks for reply:)

I started DB Browser for SQLite and added dbSeen (ALTER TABLE emails ADD COLUMN dbSeen int) column. After that it works, email report have "Duration" inside.


I uploaded my DB schema before upgrade to 102. Also DB version was 101. It's from version 2.1.0
![image](https://user-images.githubusercontent.com/5197625/50052345-01f7a200-0123-11e9-8ff2-2b60e3bf1aea.png)
[dupReport.db-schema-pre-Issue_102-upgrade.zip](https://github.com/HandyGuySoftware/dupReport/files/2683443/dupReport.db-schema-pre-Issue_102-upgrade.zip)


Would not it be best to run **initdb**? 
As I understand it, the disadvantage is that one big email will come and it will take some time (my DB size is 30MB). Is that right? Thanks :)

**Comment by HandyGuySoftware** [comment]
Running initdb (with the -i command line option) will erase and rebuild the entire database from scratch. The next time you run the program it will re-populate the database by reading and parsing all the emails from your email server, so that's what will take some time, not just one big email. You can reduce the time it takes by removing (or archiving) some of the older emails in your inbox.

-i will definitely fix the problem, but I'm still puzzled as to why it happened in the first place. If you were running v2.1.0 dR with a v1.0.2 DB the program should have crashed long ago without a dbSeen column in the DB, not just when you did the upgrade to the new code. I'm going to continue to do some research on the issue.

@brogel, which version of dupReport were you running when you made your original request?

HG

**Comment by mr-flibble** [comment]
Thanks, by big mail I mean that first report after rebuild will contain all data from all emails, or not?
EDIT: It does, I get 7MB email. 


Thanks again for duration field, now should be possible to export data and analyze backup duration growth over time (https://forum.duplicati.com/t/vacuum-performance-improvement-is-huge/5186 ) ...But I still have to figure out how best to do :)

**Comment by HandyGuySoftware** [comment]
I'm going to move the code to the pre_prod branch and see if anyone has the same problem you did. Maybe that will shed some light onto the root cause.

As for how best to do your analysis, a couple of things to keep in mind:

1. You can write out the report as a .CSV file (_-f filename.csv,csv_), which may make ingestion into an analytical program/spreadsheet easier.
2. The duration field is located in the 'report' table, which means that it is only available for the duration of the current run. Once you run dR again, the report table gets wiped out and replaced with new report data for that run. Any extraction you want to do needs to be done before the next time dR is run.

HG

**Comment by HandyGuySoftware** [comment]
@mr-flibble , you got me thinking about the new duration field. Instead of putting it in the reports table, I think I am going to move it to the emails table where it can be stored for each backup job historically. That way you will be able to keep the duration time longer than just the report run. Stay tuned...

**Comment by mr-flibble** [comment]
Thanks, i really like that idea 👍  :-)

**Comment by HandyGuySoftware** [comment]
@brogel & @mr-flibble , 

I changed the code (again) so that the duration info is now stored in the emails table instead of the report table, so it will stay in the DB until you purge emails from your server. The code has been uploaded to the [pre_prod branch](https://github.com/HandyGuySoftware/dupReport/tree/pre_prod) (version 2.2.4 Beta 2) and is available for downloading and testing.

The bad news is that if you've already tested V2.2.4 Beta 1 (as you both have) you'll need to either (1) restore your database to a pre-V2.2.4 state or (2) purge and reload the whole DB using the -i option on the command line. Unfortunately, there is no way to migrate the DB from the Beta 1 format to the Beta 2 format. Apologies for that, I should have thought this through the first time. :-(

Let me know if you encounter any issues with the new code.

HG

**Comment by mr-flibble** [comment]
Thanks! I really like that, no problem this time when I purged the DB.

Only inconvenience I encounter is CSV format - backup name is not in own column, but it's doable. 
dupReport now definitely opens new possibilities :)

This is first test chart for one backup job (containing apdata):

duration is in seconds
![image](https://user-images.githubusercontent.com/5197625/50158402-568e4f00-02d4-11e9-9c0a-56330e4f965f.png)

**Comment by HandyGuySoftware** [comment]
Looks nice! How are you running dR to get such a long time period? Are you making a special run just for this information?

**Comment by mr-flibble** [comment]
I have to run DB recreate - I don't know other way to export all records to CSV. So dR took some time (30 minutes?) to get year of data from emails.

I'm also thinking about an expert from sqlite as alternative for CSV.

**Comment by HandyGuySoftware** [comment]
Now that the durations for all the jobs are in the database, it should be easy to extract directly from there. How good are your python skills? The DB schema and examples on how to extract from the database can be found in the db.py module. The code to convert from timestamp format (the format used to store start time, end time, and duration in the db) to text is in the drdatetime.py module. Creating a custom CSV output should be relatively easy from there. Might be worth a try.

**Comment by mr-flibble** [comment]
Hi,
I'm planing to export it from sqlite DB manually, my Python skill are to low at the moment. But thanks, I will look at it later as part my Python learning:)

**Comment by HandyGuySoftware** [comment]
Sounds good. Just keep in mind that the date & time fields are stored in unix "timestamp" format, not text. There should be plenty of documentation available in multiple programming languages on ways to decode that info.
