### ISSUE TITLE
Use <details> tag for better readability of error message 

### ISSUE THREAD

**Issue by mr-flibble** [HandyGuySoftware/dupReport#34]
Hello, I thought it would be useful use  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details for collapsing error messages in report. 

I only tried it with html body fo email, not with dupReport code.

Here is how it looks like without and with details tag (collapsed).

![image](https://user-images.githubusercontent.com/5197625/33654119-6d6dbe38-da6f-11e7-8c99-30181ed5fb7e.png)

And expanded

![image](https://user-images.githubusercontent.com/5197625/33654194-a24acee8-da6f-11e7-86c8-6920be9f7929.png)

**Comment by HandyGuySoftware** [comment]
Interesting. It doesn't seem compatible with I.E. or Edge, but that's not a show-stopper. I'm wondering if this will work from the HTML engine inside of email clients like Outlook, or only works directly from a browser like Chrome or Safari. 

If you are using an email client, we can test this by updating the code a bit. In dupReport.py, Change line 694 to read:

`msgHtml = '{}<td align="center" colspan = "11"><details><summary>Error/Warning Message</summary><p><i>{}{}</i></p></details></td>'.format(msgHtml, txt[0], txt[1])`

That will tell us if it works inside an email client. I'll try this as well, but I won't be able to work on it until later tonight.

**Comment by mr-flibble** [comment]
Thank you for looking at it so fast! :)

I found this:

- Outlook 2016 - not Working
- Exchange 2013 OWA in Chrome - not Working
- Gmail in Chrome (message fwd from outlook) - Not Working

But If I save message body as html file and open it in Chrome - it Works ! :-)


Sadly "details" is on unofficial unsupported list of tags in gmail - so maybe situation will be same in other email clients. 
https://quip.com/aO0pAZO9m9SG

So I'm sorry -I should have done better research :/
I had no idea that email clients are artificially blocking HTML 5 content

**EDIT**

- Thunderbird 52 (Windows 10) - **WORKED**
- Nine mail (Android 7)  - didn't work
- Gmail with dupReport as html attachment (opening embedded in gmail on ) - didn't work

**Comment by dcurrey** [comment]
Nice!

Got the following. results.

Horde Webmail - didn't work
Roundcube webmail - didn't work
Outlook.com - didn't work
Sogo webmail - WORKED (but not with edge)
Whatever the default email client is on Samsungs phones is - WORKED
Thunderbird client - WORKED (linux)
Kmail client - WORKED (linux)

tested the webmails in vivaldi slimjet palemoon and edge all win10, Also tested firefox kubuntu 17.10

If it didn't work the message would just expand as normal.

**Comment by HandyGuySoftware** [comment]
@dcurrey , you have waaaaayyyy too many email clients to deal with! :-)

So it looks like it's hit or miss as to whether the \<details\> tag works. FYI, in 2.1 there is a feature to output the report to an HTML file (as well as text and CSV), so it should work for displaying that file if the browser supports it. 

I suppose there is no harm in including the tag in case it is supported in the target software. There is a .rc file option to show/hide messages/warnings/errors altogether, so that will counterbalance the \<details\> tag if it's not supported. I'm trying to finalize/stabilize the 2.1 code soon, but I'll try to sneak this in. 

\<advertisement\> The first beta for 2.1 should be posted on GitHub soon (hopefully by next week). Lots of new and improved features, mostly in reporting style and formatting. Keep an eye on the Duplicati announcement page for details or follow @dupReport on Twitter. I'm hoping you guys can give it a thorough shake-down. \</advertisement\>

**Comment by HandyGuySoftware** [comment]
Added to 2.1 code.
