### ISSUE TITLE
Support date format "29-Dec-17"

### ISSUE THREAD

**Issue by yakox** [HandyGuySoftware/dupReport#70]
Hi,

Could support for date format such as this be added?

EndTime: 29-Dec-17 4:01:59 PM
BeginTime: 29-Dec-17 4:00:00 PM

**Comment by HandyGuySoftware** [comment]
I'm not sure Duplicati has the ability to produce non-numeric dates in the EndTime & BeginTime lines. You'd have to check their docs to see if that's possible.

From a dupReport perspective, parsing non-numeric dates like the above is extremely difficult, since you'd need to account for the many different possible language variants (English, French, German, Czech, etc.). There's no easy, (or even manageable) way to do this with regular expression parsing.

I do know that the next version of Duplicati will include timestamps in the EndTime and BeginTime lines, such as:

`EndTime: 29-Dec-17 4:01:59 PM (154322123.0)`

When this happens, dupReport will pick up the timestamp and ignore the date specification, meaning you will be able to specify any sort of date format you want in Duplicati and dupReport will still be able to pick it up. That's in the dupReport code now, but it's not yet in the current Duplicati 2.0 Beta. I'm told it's in the test Canary builds but I haven't had a chance to try those yet.

**Comment by yakox** [comment]
I completely understand the challenge. These are dates I am getting in Duplicati emails today so I guess it is able to provide this format. I think datetime can be locale aware however I don;t have experience with that.

In any case - If I cannot change the email format I will exclude this backup set from my dupReport for now. Keep up the good work.

**Comment by dcurrey** [comment]
The Canary builds do send the emails with the timestamps.  At least the last three of four did..
~~~
EndTime: 1/2/2018 2:40:55 PM (1514922055)
BeginTime: 1/2/2018 2:40:23 PM (1514922023)
~~~

**Comment by HandyGuySoftware** [comment]
@dcurrey , yeah, @kenkendk and I discussed the change and it's coded into dR 2.1, but it's not fully tested. Now that dR 2.1 development is winding down I should download the Canaries and test with them.
