### ISSUE TITLE
e-mail log on error

### ISSUE THREAD

**Issue by ninja6o4** [HandyGuySoftware/dupReport#87]
Been busy expanding the use of Duplicati (and hence, dR).. but often forget to setup the date formatting.
With my rules setup, I only see emails if there is an error, so I don't notice if dR stops running due to a new computer with bad formatting.

Suggestion: provided that email settings are correct, can we have an option to email the log (or maybe paste the tail of it in the message body) in the event that dR aborts processing?

**Comment by HandyGuySoftware** [comment]
Interesting. To clarify, do you want to have the log sent only if dR aborts? That may be difficult, as error termination is an unplanned event and difficult to code for globally. Or, are you looking for an option to always send the log (or tail) which you'll then reference only in case you don't get a proper dR report?

**Comment by ninja6o4** [comment]
I was thinking only if dR has an error/aborts. I get that this would be hard to code for, especially if it's some unexpected error.

Maybe just a catch-all that if it bombs out for any reason but 0, send an e-mail reporting that there is some problem?

If dR exits with an error code now, I suppose an external script could be written to catch that and use another SMTP related tool to relay that email too. Just thinking out loud here..

**Comment by HandyGuySoftware** [comment]
@ninja6o4, we had a power failure last night that took out both my domain controller and main development system. I'm going to be out of commission for probably a couple of weeks while I figure out what/how to rebuild. The good news is that now I get to go shopping for new toys! :-)

I'm not sure if Python can catch a global crash. I've been doing some reading and there are some possibilities. As soon as I'm back up I'll start working on this. In the meantime, don't forget to update your date settings for new systems! ;-)

HG

**Comment by ninja6o4** [comment]
no rush!

**Comment by HandyGuySoftware** [comment]
@ninja6o4, I've done some checking into this, and the only way to globally catch an unexpected exception is to either 1) wrap the whole program into a large try/except block (or some variation of that) or 2) use a non-standard python module, which the user would have to install separately from dupReport. 

Option 1 would involve some heavy restructuring of the code, which I'm not keen on doing. It also appears to be very "non-pythonic", according to some of the comments on various python boards. Option 2 is contrary to the original purpose of the program, which was to keep the whole thing self-contained and using only standard python libraries. Unless you (or anyone else) knows of an easier way to do this, the best I can do is to continue to install localized try/except error handlers in areas of the code that seem to be problematic for most users. 

The date format handling is one of the toughest parts of the program, mostly because of the problem of distinguishing (for example) 03/04/2018 (March 4) from 03/04/2018 (April 3). There's no "perfect" way to do it, but I've tried to make it as precise as I can giving the limits of human error.

Apologies that this wasn't the outcome you were hoping for.

HG
