### ISSUE TITLE
Do mails get cleaned out serverside?

### ISSUE THREAD

**Issue by boranblok** [HandyGuySoftware/dupReport#92]
I havent read over the entire codebase yet, and I thought it might be faster to ask. But is there an option to clean processed mails from the server?

I see everything gets left behind now, wouldnt that make the process slower over time? Or will it pick up from where it left off?

Does the local database clean older data?

**Comment by HandyGuySoftware** [comment]
You are correct, there is not an option to clean email messages form the server after processing. This was done intentionally for 2 reasons:

1. I did not want dupReport to interfere with any other programs/people that might be using that email account. There is a "leave no trace" approach in the design.
1. In case the program failed mid-execution, the emails would still be available to re-run the program

In theory this does slow down the process a bit, but there are some bits in the code which work to counteract this. The program first reads only the message header (rather than the entire message) to determine if it needs to do something with a message. It also tracks which messages it has seen in the past and does not re-process messages it has already seen. But, yes, it still has to go through every single message at some level during the run.

As for the database cleanup, if you delete old emails from the account (or even just move them out of the folder specified in the .rc file) the program will purge those messages from the database and compact it to prevent the database from growing infinitely large.

Hope this addresses your issue/concern.

**Comment by boranblok** [comment]
Ok, I think I can solve both of my concerns then with an auto archiving script on the gmail side.
