### ISSUE TITLE
Is there a way to get the backup warnings without the summary report?

### ISSUE THREAD

**Issue by boranblok** [HandyGuySoftware/dupReport#93]
Like the title says, is it possible to get a backup warning without sending the full report?

Right now I report weekly on mondays with a nobackupwarn of 3 days, this in theory could make it so that a backup has not been run for 9 days before I get a warning mail. (2 days before monday, and then only next monday I get a warning)

So I would like to run dupReport daily, let it collect, but not mail a report (a daily report would be too spammy and I would tend to ignore those over time I think) but I would like it to send a backup warning if those conditions are met.

I do not know if this is possible in the current way it is programmed, or if this would be a new feature request.

**Comment by HandyGuySoftware** [comment]
@boranblok , 

It's been a while since I've been in that part of the code, but I believe if you run the program using the '-c' (collect only) option, that should suppress the main report but still send out the "No Backup" warning email if it's warranted. That would allow you to run the program daily and not get too spammy. You can then run the full program (without the '-c') once a week to get the full report as you are doing now.

Try that out and let me know if that works for you (or if it doesn't work the way I think it does ;-). If not, I'm on the road for a couple of weeks and don't have access to my development machine, but I'll take a look at it as soon as I get back.

HG

**Comment by boranblok** [comment]
That would be ideal, I will test this out, trigger a warning and see if this works.

**Comment by boranblok** [comment]
Just read a bit trough dupReport.py and if I interpret lines 230 to 256 correctly the sendBackupWarnings call is indeed outside of the if that checks for reporting and not collecting so it will always run. (if stopbackupwarn is false)

As far as I can see this will work exactly like I want it to. I'll just have to see if my day specifications work as expected (I have some backups only running every 16 days)

I'll close this issue for now and reopen it if this doesnt behave as expected.

**Comment by HandyGuySoftware** [comment]
OK, good luck. Let me know how it turns out.
